# Generated by Django 6.0.7 on 2026-07-16 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0007_remove_reminder_recipient_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito'), ('otro', 'Otro')], default='efectivo', max_length=10, verbose_name='Tipo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('metodo_captura', models.CharField(choices=[('manual', 'Manual'), ('foto', 'Foto de recibo'), ('voz', 'Voz')], default='manual', max_length=10, verbose_name='Método de captura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='vault.category')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='finanzas.cuenta', verbose_name='Cuenta')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
                ('recibo', models.ForeignKey(blank=True, help_text='Foto o documento del recibo, reutilizando tus Archivos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='vault.mediafile', verbose_name='Recibo')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
