# Generated by Django 6.0.7 on 2026-07-16 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('vault', '0007_remove_reminder_recipient_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='vault.category', verbose_name='Categoría'),
        ),
    ]
