# Generated by Django 6.0.7 on 2026-07-17 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_cuenta_numero_remove_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='numero',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El número de cuenta solo debe contener dígitos, sin espacios ni caracteres especiales.', regex='^\\d+$')], verbose_name='Número de cuenta'),
        ),
    ]
