# Generated by Django 6.0.7 on 2026-07-17 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_alter_cuenta_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deuda', models.CharField(max_length=150, verbose_name='Deuda')),
                ('tipo', models.CharField(choices=[('fija', 'Fija'), ('variable', 'Variable')], max_length=10, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto a pagar cada mes')),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo')),
                ('credito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Crédito')),
                ('dia', models.PositiveSmallIntegerField(help_text='Día del mes en que vence el pago (1-31).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Día de pago')),
                ('flag', models.CharField(choices=[('P', 'Pagado'), ('N', 'Aún sin pagar')], default='N', help_text='Estatus de pago del mes en curso.', max_length=1, verbose_name='Flag')),
                ('remarks', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deudas', to='finanzas.cuenta', verbose_name='Cuenta #')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'ordering': ['deuda'],
            },
        ),
    ]
