# Generated by Django 6.0.7 on 2026-07-17 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_deuda'),
        ('vault', '0007_remove_reminder_recipient_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='password',
            field=models.ForeignKey(blank=True, help_text='Registro de Passwords donde inicias sesión para pagar esta deuda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deudas', to='vault.vaultpassword', verbose_name='Password relacionado'),
        ),
    ]
