# Generated by Django 6.0.7 on 2026-07-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_deuda_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Obligatorio si la deuda es Fija; opcional si es Variable.', max_digits=12, null=True, verbose_name='Monto a pagar cada mes'),
        ),
    ]
