# Generated by Django 6.0.7 on 2026-07-19 15:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_alter_deuda_monto'),
        ('vault', '0008_alter_category_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['name'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='deuda',
            options={'ordering': ['deuda'], 'verbose_name': 'Debt', 'verbose_name_plural': 'Debts'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha', '-created_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='numero',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='The account number must contain only digits, no spaces or special characters.', regex='^\\d+$')], verbose_name='Account number'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Credit limit'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deudas', to='finanzas.cuenta', verbose_name='Account #'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='deuda',
            field=models.CharField(max_length=150, verbose_name='Debt'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='dia',
            field=models.PositiveSmallIntegerField(help_text='Day of the month the payment is due (1-31).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Payment day'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='flag',
            field=models.CharField(choices=[('P', 'Paid'), ('N', 'Not paid yet')], default='N', help_text='Payment status for the current month.', max_length=1, verbose_name='Paid this month'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Required if the debt is Fixed; optional if it's Variable.", max_digits=12, null=True, verbose_name='Monthly payment amount'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='password',
            field=models.ForeignKey(blank=True, help_text='Password record you use to log in and pay this debt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deudas', to='vault.vaultpassword', verbose_name='Related password'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='tipo',
            field=models.CharField(choices=[('fija', 'Fixed'), ('variable', 'Variable')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='vault.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='concepto',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='finanzas.cuenta', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='metodo_captura',
            field=models.CharField(choices=[('manual', 'Manual'), ('foto', 'Receipt photo'), ('voz', 'Voice')], default='manual', max_length=10, verbose_name='Capture method'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='recibo',
            field=models.ForeignKey(blank=True, help_text='Photo or document of the receipt, reusing your Files.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='vault.mediafile', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Income'), ('egreso', 'Expense')], max_length=10, verbose_name='Type'),
        ),
    ]
