# Generated by Django 6.0.7 on 2026-07-28 21:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_alter_cuenta_options_alter_deuda_options_and_more'),
        ('vault', '0029_remove_photoslideshowlink_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='reminder',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deuda', to='vault.reminder'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='tasa_interes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Interest rate (%)'),
        ),
    ]
