# Generated by Django 6.0.7 on 2026-09-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_deuda_reminder_deuda_tasa_interes'),
        ('vault', '0035_alter_contact_category_alter_mediafile_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='vault.category', verbose_name='Category'),
        ),
    ]
