# Generated by Django 6.0.7 on 2026-07-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='carrier',
            field=models.CharField(blank=True, help_text='Dominio de correo-a-SMS de tu compañía telefónica, incluyendo la arroba (ej. @tmomail.net para T-Mobile, @vtext.com para Verizon, @txt.att.net para AT&T). Junto con tu teléfono arma la dirección a la que KeyByMe puede mandarte avisos como si fueran un SMS, sin necesitar Twilio ni ningún otro servicio.', max_length=30, verbose_name='Carrier / pasarela SMS'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Tu número de celular, sin espacios (ej. 2407939353).', max_length=20, verbose_name='Teléfono celular'),
        ),
    ]
