# Generated by Django 6.0.7 on 2026-07-19 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_carrier_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='carrier',
            field=models.CharField(blank=True, help_text="Your phone carrier's email-to-SMS domain, including the at sign (e.g. @tmomail.net for T-Mobile, @vtext.com for Verizon, @txt.att.net for AT&T). Combined with your phone number, this builds the address KeyByMe can use to send you notifications as if they were an SMS, without needing Twilio or any other service.", max_length=30, verbose_name='Carrier / SMS gateway'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Main admin who created this account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_admin_principal',
            field=models.BooleanField(default=False, help_text='If True, this user can create/manage other accounts and their permissions.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='If True, the user cannot log in even if is_active is True.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Your mobile number, without spaces (e.g. 2407939353).', max_length=20, verbose_name='Mobile phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='storage_quota_gb',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Storage quota assigned to the user, in GB.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='storage_used_bytes',
            field=models.BigIntegerField(default=0, help_text='Space currently used, in bytes. Recalculated when files are uploaded/deleted.'),
        ),
    ]
