# Generated by Django 6.0.7 on 2026-07-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_carrier_alter_customuser_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location_alert_email',
            field=models.EmailField(blank=True, help_text="Where the 'I am here' button sends your coordinates and local time.", max_length=254, verbose_name='Location alert email'),
        ),
    ]
