# Generated by Django 6.0.7 on 2026-07-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_location_alert_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='route',
            field=models.CharField(blank=True, default='9999', help_text="Route number assigned to this user, shown on their 'I am here' check-ins.", max_length=100, verbose_name='Route'),
        ),
    ]
