# Generated by Django 6.0.7 on 2026-08-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_assign_full_access_role_to_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emergency_emails',
            field=models.CharField(blank=True, help_text="Where the 'Emergency' button sends your GPS location, date, and time. Separate multiple addresses with commas.", max_length=500, verbose_name='Emergency alert email(s)'),
        ),
    ]
