# Generated by Django 6.0.7 on 2026-09-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_verify_existing_user_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When this account was approved by the admin. Set once and never touched again — see accounts/signals.py: without it, allauth re-firing email_confirmed (e.g. a self-registered user reopening their old confirmation link, or later re-verifying a changed email) would silently re-deactivate an already-approved account.', null=True),
        ),
    ]
