# Generated by Django 6.0.7 on 2026-08-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='School name')),
                ('school_type', models.CharField(choices=[('ELEMENTARY', 'Elementary School'), ('MIDDLE', 'Middle School'), ('HIGH', 'High School')], max_length=20, verbose_name='School type')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='Zip code')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['school_type', 'name'],
            },
        ),
    ]
