# Generated by Django 6.0.7 on 2026-08-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=30, verbose_name='Route number')),
                ('route_type', models.CharField(choices=[('AM', 'AM'), ('MID', 'Mid Day'), ('PM', 'PM')], max_length=10, verbose_name='Route type')),
                ('stop_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stop #')),
                ('seq', models.PositiveIntegerField(default=10, verbose_name='Seq')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('attendant', models.ForeignKey(blank=True, limit_choices_to={'position': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendant_routes', to='schools.employee', verbose_name='Attendant')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'position': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_routes', to='schools.employee', verbose_name='Driver')),
            ],
            options={
                'verbose_name': 'Route stop',
                'verbose_name_plural': 'Routes',
                'ordering': ['route_number', 'route_type', 'seq'],
            },
        ),
    ]
