# Generated by Django 6.0.7 on 2026-08-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='bus_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Bus #'),
        ),
    ]
