# Generated by Django 6.0.7 on 2026-08-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_route_bus_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional — some rosters (e.g. bus assignment sheets) list drivers without a phone number.', max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='route',
            name='address',
            field=models.CharField(blank=True, help_text='Optional — filled in once stop-level detail is available.', max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('MID', 'Mid Day'), ('PM', 'PM')], help_text='Optional — some sources (e.g. a bus assignment roster) give the route/bus/driver without saying AM/MID/PM yet.', max_length=10, verbose_name='Route type'),
        ),
    ]
