# Generated by Django 6.0.7 on 2026-08-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_employee_phone_alter_route_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['route_number'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.RemoveField(
            model_name='route',
            name='address',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_type',
        ),
        migrations.RemoveField(
            model_name='route',
            name='seq',
        ),
        migrations.RemoveField(
            model_name='route',
            name='stop_number',
        ),
    ]
