# Generated by Django 6.0.7 on 2026-08-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_alter_route_options_remove_route_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmMidPmEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AM', 'AM'), ('MID', 'MID'), ('PM', 'PM')], max_length=3, verbose_name='Type')),
                ('seq', models.PositiveIntegerField(verbose_name='Seq #')),
                ('time', models.TimeField(verbose_name='Time')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('next', models.TimeField(blank=True, help_text='Time the bus needs to leave for the next stop, if applicable.', null=True, verbose_name='Next')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='am_mid_pm_entries', to='schools.route', verbose_name='Route')),
            ],
            options={
                'verbose_name': 'AM-MID-PM entry',
                'verbose_name_plural': 'AM-MID-PM entries',
                'ordering': ['route__route_number', 'type', 'seq'],
            },
        ),
    ]
