# Generated by Django 6.0.7 on 2026-08-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_ammidpmentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammidpmentry',
            name='next',
            field=models.TimeField(blank=True, help_text='Minutes and seconds until the next stop (MM:SS), if applicable.', null=True, verbose_name='Next'),
        ),
    ]
