# Generated by Django 6.0.7 on 2026-08-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_alter_ammidpmentry_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='ammidpmentry',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Geocoded from address by the MCPS Lefts & Rights view the first time it's opened; cached here to avoid re-geocoding on every visit.", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ammidpmentry',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
