# Generated by Django 6.0.7 on 2026-08-21 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_ammidpmentry_latitude_ammidpmentry_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ammidpmentry',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ammidpmentry',
            name='longitude',
        ),
        migrations.CreateModel(
            name='LeftRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lefts_rights', to='schools.route', verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Left & Right',
                'verbose_name_plural': 'Lefts & Rights',
                'ordering': ['route__route_number', 'name'],
                'constraints': [models.UniqueConstraint(fields=('route', 'name'), name='unique_leftright_name_per_route')],
            },
        ),
    ]
