# Generated by Django 6.0.7 on 2026-08-21 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_leftright_route_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftRightRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('row_type', models.CharField(choices=[('title', 'Title (large, bold)'), ('bold', 'Bold'), ('normal', 'Normal'), ('link', 'Link')], default='normal', max_length=10, verbose_name='Type')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='Text')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Link URL')),
                ('leftright', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='schools.leftright')),
            ],
            options={
                'verbose_name': 'Left & Right row',
                'verbose_name_plural': 'Left & Right rows',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
