# Generated by Django 6.0.7 on 2026-08-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_leftrightrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leftrightrow',
            name='url',
        ),
        migrations.AddField(
            model_name='leftrightrow',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='leftrightrow',
            name='text_after',
            field=models.CharField(blank=True, max_length=255, verbose_name='Text after'),
        ),
    ]
