# Generated by Django 6.0.7 on 2026-08-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_remove_leftrightrow_url_leftrightrow_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('url', models.CharField(max_length=500, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Depot link',
                'verbose_name_plural': 'Depot links',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
