# Generated by Django 6.0.7 on 2026-08-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_depotlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotlink',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link text'),
        ),
        migrations.AlterField(
            model_name='depotlink',
            name='url',
            field=models.CharField(max_length=500, verbose_name='Link URL'),
        ),
    ]
