# Generated by Django 6.0.7 on 2026-09-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_renumber_leftrightrow_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leftright',
            name='unique_leftright_name_per_route',
        ),
        migrations.AddField(
            model_name='depotlink',
            name='domain',
            field=models.CharField(choices=[('mcps', 'MCPS'), ('transportation', 'Transportation')], default='mcps', help_text="Which module's Depot list this link belongs to — see LeftRight.domain.", max_length=20, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='leftright',
            name='domain',
            field=models.CharField(choices=[('mcps', 'MCPS'), ('transportation', 'Transportation')], default='mcps', help_text="Which module owns this guide — MCPS and Transportation each only ever see their own. Existing rows default to MCPS, since that's the only module this ever lived under before Transportation existed.", max_length=20, verbose_name='Domain'),
        ),
        migrations.AddConstraint(
            model_name='leftright',
            constraint=models.UniqueConstraint(fields=('domain', 'route_name', 'name'), name='unique_leftright_name_per_route_per_domain'),
        ),
    ]
