# Generated by Django 6.0.7 on 2026-09-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_leftright_depotlink_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftRightAddressList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('mcps', 'MCPS'), ('transportation', 'Transportation')], default='mcps', help_text='Which module this address list belongs to — see LeftRight.domain.', max_length=20, verbose_name='Domain')),
                ('route_name', models.CharField(max_length=100, verbose_name='Route')),
                ('addresses', models.TextField(help_text='One address per line, 4 to 15 addresses, in the order they should be visited.', verbose_name='Addresses')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
            ],
            options={
                'verbose_name': 'Address list',
                'verbose_name_plural': 'Address lists',
                'ordering': ['route_name'],
                'constraints': [models.UniqueConstraint(fields=('domain', 'route_name'), name='unique_address_list_per_route_per_domain')],
            },
        ),
    ]
