# Generated by Django 6.0.7 on 2026-09-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_leftrightaddresslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftRightPhotoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('mcps', 'MCPS'), ('transportation', 'Transportation')], default='mcps', help_text='Which module this photo belongs to — see LeftRight.domain.', max_length=20, verbose_name='Domain')),
                ('route_name', models.CharField(max_length=100, verbose_name='Route')),
                ('image', models.ImageField(upload_to='leftright_photos/%Y/%m/', verbose_name='Photo')),
                ('raw_text', models.TextField(blank=True, help_text='Raw OCR output, kept for troubleshooting a bad parse.')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
            ],
            options={
                'verbose_name': 'Left & Right photo upload',
                'verbose_name_plural': 'Left & Right photo uploads',
                'ordering': ['route_name'],
                'constraints': [models.UniqueConstraint(fields=('domain', 'route_name'), name='unique_photo_upload_per_route_per_domain')],
            },
        ),
    ]
