# Generated by Django 6.0.7 on 2026-09-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_leftrightsheetupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftrightsheetupload',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='When this file was last used to generate LeftRightRow rows via "Generate from Sheet" -- shown in that picker so a route with several uploads doesn\'t get generated from the same one twice by accident. Set by LeftRightGenerateRowsFromSheetView, never by hand.', null=True, verbose_name='Used'),
        ),
    ]
