# Generated by Django 6.0.7 on 2026-07-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_category_contact_category_mediafile_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
