# Generated by Django 6.0.7 on 2026-07-11 16:34

import django.core.validators
import vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=vault.models.user_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'odt', 'ods', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'heic', 'mp4', 'mov', 'avi', 'mkv', 'webm'])]),
        ),
    ]
