# Generated by Django 6.0.7 on 2026-07-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_alter_mediafile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Cuándo se envió el correo de aviso. Vacío = todavía no se ha enviado.', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='A quién se le envía el aviso. Si se deja vacío, se usa el correo de tu cuenta.', max_length=254, verbose_name='Correo del destinatario'),
        ),
    ]
