# Generated by Django 6.0.7 on 2026-07-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_reminder_email_sent_at_reminder_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text='Formato internacional, ej. +5215512345678. Vacío = no se manda SMS.', max_length=20, verbose_name='Teléfono del destinatario (SMS)'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Cuándo se envió el SMS de aviso. Vacío = todavía no se ha enviado.', null=True),
        ),
    ]
