# Generated by Django 6.0.7 on 2026-07-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_reminder_recipient_phone_reminder_sms_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='recipient_phone',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='sms_sent_at',
        ),
        migrations.AddField(
            model_name='reminder',
            name='frequency',
            field=models.CharField(blank=True, choices=[('', 'Una sola vez'), ('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='', help_text='Una sola vez: el recordatorio se borra después de enviarse. Diario/Semanal/Mensual: se reprograma automáticamente a la misma hora (mismo día de la semana o del mes según aplique).', max_length=10, verbose_name='Frecuencia'),
        ),
    ]
