# Generated by Django 6.0.7 on 2026-07-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_remove_reminder_recipient_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['remind_at'], 'verbose_name': 'Reminder', 'verbose_name_plural': 'Reminders'},
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(choices=[('document', 'Document'), ('photo', 'Photo'), ('video', 'Video')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the notification email was sent. Empty = not sent yet.', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='frequency',
            field=models.CharField(blank=True, choices=[('', 'One time'), ('diario', 'Daily'), ('semanal', 'Weekly'), ('mensual', 'Monthly')], default='', help_text='One time: the reminder is deleted after it is sent. Daily/Weekly/Monthly: it is automatically rescheduled for the same time (same day of the week or month as applicable).', max_length=10, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='Who the notification is sent to. If left empty, your account email is used.', max_length=254, verbose_name='Recipient email'),
        ),
    ]
