# Generated by Django 6.0.7 on 2026-07-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_locationcheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcheckin',
            name='ruta',
            field=models.CharField(blank=True, max_length=100, verbose_name='Route'),
        ),
    ]
