# Generated by Django 6.0.7 on 2026-07-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0010_locationcheckin_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationcheckin',
            name='ruta',
        ),
        migrations.AddField(
            model_name='locationcheckin',
            name='seq',
            field=models.PositiveIntegerField(default=10, verbose_name='Seq'),
        ),
    ]
