# Generated by Django 6.0.7 on 2026-07-20 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_check_date(apps, schema_editor):
    LocationCheckIn = apps.get_model('vault', 'LocationCheckIn')
    for checkin in LocationCheckIn.objects.filter(check_date__isnull=True):
        checkin.check_date = timezone.localtime(checkin.created_at).date()
        checkin.save(update_fields=['check_date'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0011_remove_locationcheckin_ruta_locationcheckin_seq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationcheckin',
            options={'ordering': ['-check_date', 'seq'], 'verbose_name': 'Location check-in', 'verbose_name_plural': 'Location check-ins'},
        ),
        migrations.AddField(
            model_name='locationcheckin',
            name='check_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.RunPython(backfill_check_date, noop),
        migrations.AlterField(
            model_name='locationcheckin',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='locationcheckin',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='locationcheckin',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(default=10, verbose_name='Seq')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily route stop',
                'verbose_name_plural': 'Daily route stops',
                'ordering': ['seq'],
            },
        ),
    ]
