# Generated by Django 6.0.7 on 2026-07-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0013_alter_locationcheckin_check_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestop',
            options={'ordering': ['route_type', 'seq'], 'verbose_name': 'Daily route stop', 'verbose_name_plural': 'Daily route stops'},
        ),
        migrations.AddField(
            model_name='locationcheckin',
            name='route_type',
            field=models.CharField(blank=True, help_text='Which saved route (AM, PM, MID DAY, ...) this stop was loaded from, if any.', max_length=30, verbose_name='Route type'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='route_type',
            field=models.CharField(default='AM', max_length=30, verbose_name='Route type'),
        ),
    ]
