# Generated by Django 6.0.7 on 2026-07-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0014_alter_routestop_options_locationcheckin_route_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcheckin',
            name='stop_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stop #'),
        ),
    ]
