# Generated by Django 6.0.7 on 2026-07-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0015_locationcheckin_stop_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcheckin',
            name='is_closed',
            field=models.BooleanField(default=False, help_text="Set by the 'Close day' button: moves this check-in from today's 'I am here' table into History, without waiting for the calendar date to change."),
        ),
    ]
