# Generated by Django 6.0.7 on 2026-07-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0016_locationcheckin_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='stop_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stop #'),
        ),
    ]
