# Generated by Django 6.0.7 on 2026-07-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0017_routestop_stop_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='planned_time',
            field=models.TimeField(blank=True, help_text='Reference time this stop is expected to happen — not the actual captured time.', null=True, verbose_name='Time'),
        ),
    ]
