# Generated by Django 6.0.7 on 2026-07-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0018_routestop_planned_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcheckin',
            name='is_loaded',
            field=models.BooleanField(default=True, help_text="False only for a working-copy row Dispatch pre-created on Close day that the driver hasn't loaded yet via the route button on I am here."),
        ),
        migrations.AlterField(
            model_name='locationcheckin',
            name='is_closed',
            field=models.BooleanField(default=False, help_text="Set by Dispatch's 'Close day': moves this check-in from I am here (and Dispatch) into History."),
        ),
    ]
