# Generated by Django 6.0.7 on 2026-07-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0019_locationcheckin_is_loaded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationcheckin',
            name='is_loaded',
        ),
        migrations.AlterField(
            model_name='locationcheckin',
            name='is_closed',
            field=models.BooleanField(default=False, help_text="Set by Dispatch's 'Close day': moves this check-in from today's 'I am here' table into History, without waiting for the calendar date to change."),
        ),
    ]
