# Generated by Django 6.0.7 on 2026-07-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0020_remove_locationcheckin_is_loaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
