# Generated by Django 6.0.7 on 2026-07-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0021_routestop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcheckin',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
