# Generated by Django 6.0.7 on 2026-07-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0023_backfill_checkin_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
    ]
