# Generated by Django 6.0.7 on 2026-07-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0024_routestop_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcheckin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
    ]
