# Generated by Django 6.0.7 on 2026-07-23 23:31

import django.core.validators
import django.db.models.deletion
import uuid
import vault.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0025_locationcheckin_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Make')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('license_plate', models.CharField(blank=True, max_length=20, verbose_name='License plate')),
                ('insurance_broker_phone', models.CharField(blank=True, max_length=30, verbose_name='Insurance broker phone')),
                ('insurance_card', models.FileField(blank=True, null=True, upload_to=vault.models.user_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='Insurance card')),
                ('_pin_hash', models.CharField(db_column='pin_hash', editable=False, max_length=128)),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['make', 'model', '-year'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Date')),
                ('performed_by', models.CharField(max_length=150, verbose_name='Performed by (company or person)')),
                ('mileage', models.PositiveIntegerField(verbose_name='Mileage')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_via_public_link', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vault.vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance record',
                'verbose_name_plural': 'Maintenance records',
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
