# Generated by Django 6.0.7 on 2026-07-24 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0026_vehicle_maintenancerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('general', 'General'), ('files', 'Files')], default='general', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('owner', 'name', 'kind')},
        ),
    ]
