# Generated by Django 6.0.7 on 2026-07-24 23:32

from django.db import migrations, models


def copy_category_to_categories(apps, schema_editor):
    """Preserva los links ya creados con el viejo FK 'category' antes de
    borrarlo, agregando esa misma categoría al nuevo M2M 'categories'."""
    PhotoSlideshowLink = apps.get_model('vault', 'PhotoSlideshowLink')
    for link in PhotoSlideshowLink.objects.exclude(category__isnull=True):
        link.categories.add(link.category_id)


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0028_photoslideshowlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoslideshowlink',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='+', to='vault.category'),
        ),
        migrations.RunPython(copy_category_to_categories, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='photoslideshowlink',
            name='category',
        ),
    ]
