# Generated by Django 6.0.7 on 2026-08-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0029_remove_photoslideshowlink_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geocoded from address by RouteDirectionsView the first time Directions is opened; cached here to avoid re-geocoding on every visit.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
