# Generated by Django 6.0.7 on 2026-08-04 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0030_routestop_latitude_routestop_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSheetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='route_sheets/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_text', models.TextField(blank=True, help_text='Raw OCR output, kept for troubleshooting a bad parse.')),
                ('route_number', models.CharField(blank=True, help_text='Must match an existing driver\'s "Route" field to Import.', max_length=100, verbose_name='Route number')),
                ('route_type', models.CharField(blank=True, max_length=30, verbose_name='Route type')),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_sheet_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Route sheet upload',
                'verbose_name_plural': 'Route sheet uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteSheetStopDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(default=10, verbose_name='Seq')),
                ('planned_time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('include', models.BooleanField(default=True, help_text='Uncheck to skip this row on Import (e.g. a garbled OCR read).', verbose_name='Include')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_stops', to='vault.routesheetupload')),
            ],
            options={
                'verbose_name': 'Route sheet draft stop',
                'verbose_name_plural': 'Route sheet draft stops',
                'ordering': ['seq'],
            },
        ),
    ]
