# Generated by Django 6.0.7 on 2026-08-14 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0031_routesheetupload_routesheetstopdraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Phone number')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('', 'Unknown')], max_length=3, verbose_name='Blood type')),
                ('medical_conditions', models.TextField(blank=True, help_text='Diagnosed conditions a first responder should know about (e.g. diabetes, epilepsy, heart condition).', verbose_name='Medical conditions')),
                ('allergies', models.TextField(blank=True, help_text='Medication, food, or other allergies — and the reaction, if severe.', verbose_name='Allergies')),
                ('medications', models.TextField(blank=True, help_text='One per line, including dosage if known.', verbose_name='Current medications')),
                ('organ_donor', models.BooleanField(default=False, verbose_name='Organ donor')),
                ('primary_doctor_name', models.CharField(blank=True, max_length=150, verbose_name='Primary doctor name')),
                ('primary_doctor_phone', models.CharField(blank=True, max_length=30, verbose_name='Primary doctor phone')),
                ('insurance_provider', models.CharField(blank=True, max_length=150, verbose_name='Insurance provider')),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, verbose_name='Insurance policy number')),
                ('emergency_contact_1_name', models.CharField(max_length=150, verbose_name='Emergency contact 1 — name')),
                ('emergency_contact_1_phone', models.CharField(max_length=30, verbose_name='Emergency contact 1 — phone')),
                ('emergency_contact_1_relationship', models.CharField(blank=True, max_length=100, verbose_name='Emergency contact 1 — relationship')),
                ('emergency_contact_2_name', models.CharField(blank=True, max_length=150, verbose_name='Emergency contact 2 — name')),
                ('emergency_contact_2_phone', models.CharField(blank=True, max_length=30, verbose_name='Emergency contact 2 — phone')),
                ('emergency_contact_2_relationship', models.CharField(blank=True, max_length=100, verbose_name='Emergency contact 2 — relationship')),
                ('emergency_contact_3_name', models.CharField(blank=True, max_length=150, verbose_name='Emergency contact 3 — name')),
                ('emergency_contact_3_phone', models.CharField(blank=True, max_length=30, verbose_name='Emergency contact 3 — phone')),
                ('emergency_contact_3_relationship', models.CharField(blank=True, max_length=100, verbose_name='Emergency contact 3 — relationship')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Additional notes')),
                ('_pin_hash', models.CharField(db_column='pin_hash', editable=False, max_length=128)),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical record',
                'verbose_name_plural': 'Medical records',
                'ordering': ['full_name'],
            },
        ),
    ]
