# Generated by Django 6.0.7 on 2026-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0032_medicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('general', 'General (legacy)'), ('files', 'Files'), ('contacts', 'Contacts'), ('passwords', 'Passwords'), ('links', 'Links'), ('reminders', 'Reminders'), ('finanzas', 'Finances')], default='general', max_length=10),
        ),
    ]
