# Generated by Django 6.0.7 on 2026-09-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0034_split_general_categories_per_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='vault.category'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_files', to='vault.category'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='vault.category'),
        ),
        migrations.AlterField(
            model_name='url',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='urls', to='vault.category'),
        ),
        migrations.AlterField(
            model_name='vaultpassword',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passwords', to='vault.category'),
        ),
    ]
