# Generated by Django 6.0.7 on 2026-09-05 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0035_alter_contact_category_alter_mediafile_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesheetupload',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_sheet_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
