# Generated by Django 6.0.7 on 2026-07-10 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('codename', models.SlugField(help_text="Identificador usado en el código, ej: 'contacts'", max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Nombre de ícono (ej: para Bootstrap Icons o FontAwesome)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codename', models.SlugField(help_text="Ej: 'docs.upload'", max_length=150, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='menus.module')),
            ],
            options={
                'verbose_name': 'Submódulo',
                'verbose_name_plural': 'Submódulos',
                'ordering': ['module__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.role')),
                ('submodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.submodule')),
            ],
            options={
                'verbose_name': 'Permiso de rol',
                'verbose_name_plural': 'Permisos de rol',
                'unique_together': {('role', 'submodule')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='submodules',
            field=models.ManyToManyField(related_name='roles', through='menus.RolePermission', to='menus.submodule'),
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True, help_text='True = otorgar acceso extra, False = revocar acceso del rol')),
                ('submodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.submodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excepción de permiso',
                'verbose_name_plural': 'Excepciones de permiso',
                'unique_together': {('user', 'submodule')},
            },
        ),
    ]
