# Generated by Django 6.0.7 on 2026-07-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'Role permission', 'verbose_name_plural': 'Role permissions'},
        ),
        migrations.AlterModelOptions(
            name='submodule',
            options={'ordering': ['module__order', 'order', 'name'], 'verbose_name': 'Submodule', 'verbose_name_plural': 'Submodules'},
        ),
        migrations.AlterModelOptions(
            name='userpermissionoverride',
            options={'verbose_name': 'Permission override', 'verbose_name_plural': 'Permission overrides'},
        ),
        migrations.AlterField(
            model_name='module',
            name='codename',
            field=models.SlugField(help_text="Identifier used in code, e.g. 'contacts'", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name (e.g. for Bootstrap Icons or FontAwesome)', max_length=50),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='codename',
            field=models.SlugField(help_text="E.g. 'docs.upload'", max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='userpermissionoverride',
            name='granted',
            field=models.BooleanField(default=True, help_text='True = grant extra access, False = revoke role access'),
        ),
    ]
