# Generated by Django 6.0.7 on 2026-07-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_module_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.PositiveIntegerField(default=0, help_text="Numeric rank used to gate level-based features (e.g. a user needs level > 70 to see 'History' on I am here)."),
        ),
    ]
