# Generated by Django 6.0.7 on 2026-08-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='Modules a user with this role can access (shown as on/off switches).', related_name='roles', to='menus.module'),
        ),
    ]
