# Generated by Django 6.0.7 on 2026-09-03 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_seed_medical_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModuleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True, help_text="True = grant access, False = revoke access, regardless of the user's Roles.")),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module override',
                'verbose_name_plural': 'Module overrides',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
